# Generated by Django 4.2.29 on 2026-03-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plain_password',
            field=models.CharField(blank=True, help_text='Password as entered during registration (visible to admin only)', max_length=128),
        ),
    ]
