# Generated by Django 4.2.29 on 2026-03-07 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_plain_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='plain_password',
        ),
    ]
