# Generated by Django 4.2.29 on 2026-03-06 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('text', models.TextField()),
                ('option_a', models.TextField()),
                ('option_b', models.TextField()),
                ('option_c', models.TextField()),
                ('option_d', models.TextField()),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explanation', models.TextField(help_text='Step-by-step explanation of the correct answer')),
                ('source', models.CharField(blank=True, default='Custom', max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='📚', max_length=50)),
                ('test_duration_minutes', models.PositiveIntegerField(default=25)),
                ('questions_per_test', models.PositiveIntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('timed_out', 'Timed Out')], default='in_progress', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('total_questions', models.PositiveIntegerField(default=20)),
                ('correct_count', models.PositiveIntegerField(blank=True, null=True)),
                ('incorrect_count', models.PositiveIntegerField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='practice.subject')),
            ],
            options={
                'unique_together': {('subject', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('selected_answer', models.CharField(blank=True, max_length=1, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('marked_for_review', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.question')),
                ('test_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='practice.testattempt')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('test_attempt', 'order')},
            },
        ),
        migrations.AddField(
            model_name='testattempt',
            name='questions',
            field=models.ManyToManyField(through='practice.TestQuestion', to='practice.question'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.subject'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='practice.subject'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='practice.topic'),
        ),
    ]
